name: Build

on:
  push:
    branches:
      - "**"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 21.6.2

      - name: Change Directory
        run: cd frontend-next

      - name: Install dependencies
        run: npm install

      - name: Buide
        run: npm run build
