name: Next.Js Build Validation

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  nextjs:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 21.6.2

      - name: Install dependencies
        run: npm install frontend-next/

      - name: Build
        run: npm --prefix frontend-next/ run build
